name: Build and upload SDK

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-web-packages-n-create-tag:
    runs-on: ubuntu-latest

    name: Build Web SDK & Deliver JS file to S3

    steps:
      - uses: actions/checkout@v4

      - name: Set release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - id: set-version
        run: echo "version=${{ env.RELEASE_VERSION }}" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.3

      - name: Build SDK
        run: |
          pnpm i
          pnpm build

      - name: Create dist version tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ env.RELEASE_VERSION }}-dist
          git push origin ${{ env.RELEASE_VERSION }}-dist

  send-failure:
    name: Send failure notify
    if: failure()
    runs-on: ubuntu-latest
    needs:
      - build-web-packages-n-create-tag
    steps:
      - name: Send failure notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_ID }}
          message: |
            ${{ github.workflow }} is failure on "${{ github.repository }}"
            ${{ github.repositoryUrl }}

  send-success:
    name: Send success notify
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build-web-packages-n-create-tag
    steps:
      - name: Send success notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_ID }}
          message: |
            ${{ github.workflow }} is success on "${{ github.repository }}"
            ${{ github.repositoryUrl }}
